In [107]:
import numpy as np
import pandas as pd

In [108]:
fish = pd.read_csv('https://raw.githubusercontent.com/wizard113/ML-Basic/main/fish_data.csv')

In [109]:
fish.head()

  Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961
3   Bream   363.0    29.0      33.5  12.7300  4.4555
4   Bream   430.0    29.0      34.0  12.4440  5.1340

In [110]:
fish.describe()

            Weight      Length    Diagonal      Height       Width
count   159.000000  159.000000  159.000000  159.000000  159.000000
mean    398.326415   28.415723   31.227044    8.970994    4.417486
std     357.978317   10.716328   11.610246    4.286208    1.685804
min       0.000000    8.400000    8.800000    1.728400    1.047600
25%     120.000000   21.000000   23.150000    5.944800    3.385650
50%     273.000000   27.300000   29.400000    7.786000    4.248500
75%     650.000000   35.500000   39.650000   12.365900    5.584500
max    1650.000000   63.400000   68.000000   18.957000    8.142000

In [111]:
## Data, Target 분리

In [112]:
np.unique(fish['Species'], return_counts=True)

(array(['Bream', 'Parkki', 'Perch', 'Pike', 'Roach', 'Smelt', 'Whitefish'],
       dtype=object),
 array([35, 11, 56, 17, 20, 14,  6]))

In [113]:
fish.columns

Index(['Species', 'Weight', 'Length', 'Diagonal', 'Height', 'Width'], dtype='object')

In [114]:
input= fish[['Weight', 'Length', 'Diagonal', 'Height', 'Width']].to_numpy()
target = fish['Species'].to_numpy()

In [115]:
from sklearn.preprocessing import StandardScaler

In [116]:
# 표준화
ss = StandardScaler()
ss.fit(input)
input_scaled = ss.transform(input)
print(input_scaled[0])

[-0.43807217 -0.28230301 -0.10602023  0.59657867 -0.23652895]

In [117]:
## Train, Test 분리

In [118]:
from sklearn.model_selection import train_test_split

In [119]:
from sklearn.preprocessing import LabelEncoder

In [120]:
x_train, x_test, y_train, y_test = train_test_split(input_scaled, target, test_size=0.2, random_state=23)

In [121]:
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)

(127, 5) (32, 5)
(127,) (32,)

In [122]:
## Model 생성

In [123]:
from tensorflow.keras import models, layers, utils

In [124]:
model = models.Sequential()
model = models.Sequential([
    layers.Dense(16, activation='relu', input_shape=(5,)),
    layers.Dense(8, activation='relu'),
    layers.Dense(7, activation='softmax')  # 물고기 종류 7개
])
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_14 (Dense)                │ (None, 16)             │            96 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 7)              │            63 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 295 (1.15 KB)

 Trainable params: 295 (1.15 KB)

 Non-trainable params: 0 (0.00 B)

In [125]:
print(y_train.shape, y_test.shape)

(127,) (32,)

In [126]:
print(y_train)

['Bream' 'Pike' 'Parkki' 'Perch' 'Pike' 'Smelt' 'Perch' 'Perch' 'Roach'
 'Perch' 'Perch' 'Pike' 'Parkki' 'Bream' 'Perch' 'Whitefish' 'Perch'
 'Roach' 'Smelt' 'Bream' 'Pike' 'Bream' 'Perch' 'Bream' 'Bream' 'Perch'
 'Pike' 'Perch' 'Perch' 'Pike' 'Pike' 'Smelt' 'Roach' 'Perch' 'Perch'
 'Perch' 'Bream' 'Bream' 'Perch' 'Roach' 'Perch' 'Bream' 'Perch' 'Perch'
 'Bream' 'Bream' 'Pike' 'Roach' 'Smelt' 'Perch' 'Pike' 'Pike' 'Perch'
 'Roach' 'Bream' 'Smelt' 'Bream' 'Bream' 'Pike' 'Perch' 'Perch' 'Perch'
 'Bream' 'Perch' 'Perch' 'Parkki' 'Perch' 'Perch' 'Perch' 'Roach' 'Parkki'
 'Perch' 'Roach' 'Parkki' 'Bream' 'Whitefish' 'Perch' 'Perch' 'Parkki'
 'Parkki' 'Perch' 'Smelt' 'Smelt' 'Pike' 'Bream' 'Perch' 'Perch' 'Bream'
 'Smelt' 'Smelt' 'Bream' 'Perch' 'Perch' 'Smelt' 'Roach' 'Bream'
 'Whitefish' 'Bream' 'Whitefish' 'Roach' 'Perch' 'Bream' 'Perch' 'Perch'
 'Bream' 'Perch' 'Pike' 'Parkki' 'Roach' 'Smelt' 'Whitefish' 'Smelt'
 'Perch' 'Roach' 'Roach' 'Bream' 'Smelt' 'Roach' 'Bream' 'Perch' 'Bream'
 'Perch' 'Roach' 'Perch' 'Bream' 'Roach' 'Perch']

In [127]:
# 문자열 → 숫자 : one-hot encoding을 위함(여기서는 사용하지 않아도 됨)
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [128]:
# one-hot encoding : 분류이므로 사용하지 않아도 됨
y_train_oh = utils.to_categorical(y_train)
y_test_oh = utils.to_categorical(y_test)
print(y_train_oh.shape, y_test_oh.shape)

(127, 7) (32, 7)

In [129]:
print(y_train_oh[:10])

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]]

In [130]:
# 분류이므로 sparse_categorical_crossentropy
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [131]:
model.fit(x_train, y_train, epochs=100)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.2126 - loss: 1.8641
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2205 - loss: 1.8317
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2205 - loss: 1.7997
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.2205 - loss: 1.7721
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2205 - loss: 1.7459
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2283 - loss: 1.7242
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2283 - loss: 1.7014
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2283 - loss: 1.6818
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2283 - loss: 1.6635
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2283 - loss: 1.6457
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2283 - loss: 1.6299
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2362 - loss: 1.6151
Epoch 13/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2441 - loss: 1.6004
Epoch 14/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2520 - loss: 1.5863
Epoch 15/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2756 - loss: 1.5734
Epoch 16/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2835 - loss: 1.5601
Epoch 17/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2992 - loss: 1.5478
Epoch 18/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.3071 - loss: 1.5352
Epoch 19/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3465 - loss: 1.5240
Epoch 20/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4488 - loss: 1.5121
Epoch 21/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4961 - loss: 1.5003
Epoch 22/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5354 - loss: 1.4896
Epoch 23/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5591 - loss: 1.4784
Epoch 24/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5669 - loss: 1.4670
Epoch 25/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5906 - loss: 1.4564
Epoch 26/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6063 - loss: 1.4454
Epoch 27/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6063 - loss: 1.4355
Epoch 28/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5984 - loss: 1.4245
Epoch 29/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6142 - loss: 1.4135
Epoch 30/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6457 - loss: 1.4029
Epoch 31/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6457 - loss: 1.3925
Epoch 32/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6535 - loss: 1.3814
Epoch 33/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6457 - loss: 1.3712
Epoch 34/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6457 - loss: 1.3602
Epoch 35/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6457 - loss: 1.3499
Epoch 36/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6457 - loss: 1.3384
Epoch 37/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6457 - loss: 1.3277
Epoch 38/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6457 - loss: 1.3167
Epoch 39/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6535 - loss: 1.3052
Epoch 40/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6535 - loss: 1.2948
Epoch 41/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6535 - loss: 1.2835
Epoch 42/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6535 - loss: 1.2724
Epoch 43/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6457 - loss: 1.2619
Epoch 44/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6457 - loss: 1.2505
Epoch 45/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6535 - loss: 1.2398
Epoch 46/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6535 - loss: 1.2285
Epoch 47/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6614 - loss: 1.2181
Epoch 48/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6614 - loss: 1.2068
Epoch 49/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6614 - loss: 1.1961
Epoch 50/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6614 - loss: 1.1846
Epoch 51/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6614 - loss: 1.1741
Epoch 52/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6614 - loss: 1.1634
Epoch 53/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6693 - loss: 1.1527
Epoch 54/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6693 - loss: 1.1419
Epoch 55/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6693 - loss: 1.1306
Epoch 56/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6693 - loss: 1.1198
Epoch 57/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6772 - loss: 1.1092
Epoch 58/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6929 - loss: 1.0997
Epoch 59/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6929 - loss: 1.0882
Epoch 60/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7008 - loss: 1.0772
Epoch 61/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7087 - loss: 1.0674
Epoch 62/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7087 - loss: 1.0565
Epoch 63/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7008 - loss: 1.0470
Epoch 64/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7087 - loss: 1.0366
Epoch 65/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7244 - loss: 1.0261
Epoch 66/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7244 - loss: 1.0165
Epoch 67/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7165 - loss: 1.0066
Epoch 68/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7165 - loss: 0.9971
Epoch 69/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7165 - loss: 0.9870
Epoch 70/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7165 - loss: 0.9771
Epoch 71/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7323 - loss: 0.9684
Epoch 72/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7323 - loss: 0.9581
Epoch 73/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7323 - loss: 0.9494
Epoch 74/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7323 - loss: 0.9398
Epoch 75/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7323 - loss: 0.9302
Epoch 76/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7323 - loss: 0.9212
Epoch 77/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7402 - loss: 0.9123
Epoch 78/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7402 - loss: 0.9035
Epoch 79/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7402 - loss: 0.8949
Epoch 80/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7402 - loss: 0.8861
Epoch 81/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7402 - loss: 0.8778
Epoch 82/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7402 - loss: 0.8690
Epoch 83/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7402 - loss: 0.8608
Epoch 84/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7402 - loss: 0.8531
Epoch 85/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7402 - loss: 0.8443
Epoch 86/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7402 - loss: 0.8361
Epoch 87/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7402 - loss: 0.8290
Epoch 88/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7480 - loss: 0.8211
Epoch 89/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7480 - loss: 0.8135
Epoch 90/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7559 - loss: 0.8067
Epoch 91/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7559 - loss: 0.7993
Epoch 92/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7559 - loss: 0.7913
Epoch 93/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7559 - loss: 0.7854
Epoch 94/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7559 - loss: 0.7779
Epoch 95/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7559 - loss: 0.7708
Epoch 96/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7559 - loss: 0.7646
Epoch 97/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7559 - loss: 0.7577
Epoch 98/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7638 - loss: 0.7511
Epoch 99/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7638 - loss: 0.7450
Epoch 100/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7638 - loss: 0.7386

In [132]:
# 모델 평가
model.evaluate(x_test, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - accuracy: 0.7812 - loss: 0.6559

[0.6559151411056519, 0.78125]

In [133]:
y_test[:10]

array([5, 2, 2, 2, 0, 2, 2, 2, 0, 3])

In [134]:
# 예측
pred = model.predict(x_test[:10])
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
[[3.96608339e-05 2.45395191e-02 2.17894241e-01 6.43815380e-04
  1.17017321e-01 6.39792323e-01 7.31798937e-05]
 [4.99930494e-02 2.91903899e-03 6.93514764e-01 1.57382563e-01
  3.51118557e-02 3.26545537e-02 2.84242053e-02]
 [4.04391874e-04 6.76920936e-02 4.50245708e-01 3.35934991e-03
  2.47494444e-01 2.29718000e-01 1.08608243e-03]
 [3.57770063e-02 3.77090387e-02 5.63598335e-01 1.23855904e-01
  1.12490065e-01 4.71287258e-02 7.94407874e-02]
 [8.20238650e-01 6.25826826e-04 5.41380718e-02 8.03212300e-02
  1.02321086e-02 1.97599139e-02 1.46842487e-02]
 [3.87555435e-02 9.14391130e-04 7.58119524e-01 1.43441200e-01
  2.05248259e-02 2.17448194e-02 1.64995808e-02]
 [5.40091249e-04 4.89205122e-02 5.58165073e-01 4.79349587e-03
  2.03652352e-01 1.82436958e-01 1.49139983e-03]
 [3.09627969e-02 1.86871275e-05 8.07128072e-01 1.49265319e-01
  3.49893793e-03 5.43676084e-03 3.68947536e-03]
 [7.66079843e-01 6.45779422e-04 7.87908435e-02 1.03886716e-01
  1.14721777e-02 2.19114535e-02 1.72132440e-02]
 [2.79736966e-02 2.39105361e-07 2.88374238e-02 9.34827685e-01
  8.83416506e-05 3.14430625e-04 7.95801263e-03]]

In [135]:
pred_index = np.argmax(pred, axis=1)
print(pred_index)

[5 2 2 2 0 2 2 2 0 3]

In [137]:
fish_type = ['Bream', 'Parkki', 'Perch', 'Pike', 'Roach', 'Smelt', 'Whitefish']
for p in pred_index:
  print(fish_type[p])

Smelt
Perch
Perch
Perch
Bream
Perch
Perch
Perch
Bream
Pike